### ISSUE TITLE
Need to be able to build a production version of the client

### ISSUE THREAD

**Issue by joethe** [UMM-CSci-3601/production-template#3]
Currently it seems as though everything in the client is set up only for development (webpack, etc).

We need to be able to have webpack build us a client side that can be packaged up with the spark server.

Alternatively, we could think about maintaining our client-side / API separation and continue to have the client side of the project served up by a separate webserver. This may simplify some things for us, but I think we'll still need to add another webpack configuration...

Thoughts @devshawn ? @NicMcPhee ?

**Comment by NicMcPhee** [comment]
This may be resolved by pull request #6 but I'm not 100% if they line up completely?

**Comment by joethe** [comment]
Actually, I think this may have been addressed by the two commits mentioned in the issue history. I guess it just never got closed....

**Comment by NicMcPhee** [comment]
The work in #6 is actually just part (but not all) of #2, and not part of this at all?

**Comment by joethe** [comment]
I believe so, yes.
