### ISSUE TITLE
Update rubric for iteration 1

### ISSUE THREAD

**Issue by kklamberty** [UMM-CSci-3601/production-template#7]
The rubric for iteration 1 currently has "testing angular", and we probably want to alter that to be "testing" (that includes server as well as client) or make some change that allows for both flexibility in what happens in the iteration AND encouragement for good practice of testing whatever you have.

**Comment by joethe** [comment]
What's the status on this?

**Comment by kklamberty** [comment]
We updated the rubric for this iteration, but we added a wider variety of specifics rather than removing them or making things more general. This year, the students have seen end-to-end tests, angular tests, and tests in Java, so we are expecting they will have had some of these experiences.
